/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Ninth.glb 
*/

import React, { useEffect, useState, useMemo, useRef } from "react";
import { useGLTFWithKTX2 } from "../utils/useGLTFWithKTX2";
import { convertMaterialsToBasic } from "../utils/convertToBasic";
import * as THREE from "three";
import { useModalStore } from "../../stores/useModalStore";
import { useTexture } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

// Default dimensions (Width x Height) - change these values anytime!
const EMBLEM_WIDTH = 1.6;
const EMBLEM_HEIGHT = 2.1;

const WallEmblemItem = ({
  id,
  title,
  texturePath,
  position,
  width = EMBLEM_WIDTH,
  height = EMBLEM_HEIGHT,
  progress,
  pulseIntensity,
  isModalOpen,
  hoveredMesh,
  setHoveredMesh,
  handleClick,
}) => {
  const texture = useTexture(texturePath);
  const isHovered = hoveredMesh === id;
  const isInteractable = progress >= 0.399 && progress <= 0.6 && !isModalOpen;

  const groupRef = useRef();

  useFrame((_, delta) => {
    if (!groupRef.current) return;
    // Target position z offset for hover exposure off the wall
    const targetZ = isHovered && isInteractable ? position[2] + 0.18 : position[2];
    groupRef.current.position.z = THREE.MathUtils.lerp(
      groupRef.current.position.z,
      targetZ,
      delta * 8
    );
  });

  const goldGlowColor = useMemo(() => {
    const pulse = 1 + pulseIntensity * 0.8;
    return isHovered
      ? "#ffe082"
      : `rgb(${Math.floor(180 * pulse)}, ${Math.floor(140 * pulse)}, ${Math.floor(70 * pulse)})`;
  }, [isHovered, pulseIntensity]);

  return (
    <group
      ref={groupRef}
      position={[position[0], position[1], position[2]]}
      onPointerOver={(e) => {
        e.stopPropagation();
        if (isInteractable) setHoveredMesh(id);
      }}
      onPointerOut={(e) => {
        e.stopPropagation();
        setHoveredMesh(null);
      }}
      onClick={(e) => {
        e.stopPropagation();
        if (isInteractable) handleClick(id);
      }}
    >
      {/* 3D Dark Obsidian Stone Backing Plaque (Stuck to wall, exposing depth) */}
      <mesh position={[0, 0, -0.05]}>
        <boxGeometry args={[width + 0.08, height + 0.08, 0.12]} />
        <meshStandardMaterial
          color={isHovered ? "#26221c" : "#141312"}
          roughness={0.8}
          metalness={0.4}
        />
      </mesh>

      {/* 3D Dark Gold Metallic Beveled Border Frame */}
      <mesh position={[0, 0, 0]}>
        <boxGeometry args={[width + 0.14, height + 0.14, 0.06]} />
        <meshStandardMaterial
          color={goldGlowColor}
          roughness={0.3}
          metalness={0.85}
          emissive={isHovered ? "#ffaa00" : "#332200"}
          emissiveIntensity={isHovered ? 0.65 : 0.15}
        />
      </mesh>

      {/* Front Textured Emblem Relief Face */}
      <mesh position={[0, 0, 0.04]}>
        <planeGeometry args={[width, height]} />
        <meshBasicMaterial map={texture} />
      </mesh>
    </group>
  );
};

export default function Model({ progress = 0, pulseIntensity = 0, ...props }) {
  const { nodes, materials } = useGLTFWithKTX2("/models/Ninth.glb");
  const [hoveredMesh, setHoveredMesh] = useState(null);
  const { openModal, setModalID, isModalOpen } = useModalStore();

  const newMaterials = useMemo(
    () => convertMaterialsToBasic(materials),
    [materials]
  );

  useEffect(() => {
    if (progress <= 0.399 || progress >= 0.6 || isModalOpen) return;
    document.body.style.cursor = hoveredMesh ? "pointer" : "auto";

    return () => {
      document.body.style.cursor = "auto";
    };
  }, [hoveredMesh, progress, isModalOpen]);

  const handleClick = (elementID) => {
    if (progress <= 0.399 || progress >= 0.6 || isModalOpen) return;
    openModal();
    setModalID(elementID);
  };

  const emblemItems = useMemo(
    () => [
      {
        id: "about",
        title: "ABOUT",
        texturePath: "/textures/valyria_about.png",
        position: [-0.457, 9.285, -48.4],
      },
      {
        id: "events",
        title: "EVENTS",
        texturePath: "/textures/valyria_events.png",
        position: [2.778, 9.285, -48.4],
      },
      {
        id: "schedule",
        title: "SCHEDULE",
        texturePath: "/textures/valyria_schedule.png",
        position: [6.136, 9.285, -48.4],
      },
      {
        id: "staff_coordinators",
        title: "STAFF COORDINATORS",
        texturePath: "/textures/valyria_staff.png",
        position: [9.538, 9.285, -48.4],
      },
      {
        id: "zyverse_team",
        title: "ZYVERSE TEAM",
        texturePath: "/textures/valyria_team.png",
        position: [12.806, 9.285, -48.4],
      },
    ],
    []
  );

  return (
    <group {...props} dispose={null}>
      {emblemItems.map((item) => (
        <WallEmblemItem
          key={item.id}
          id={item.id}
          title={item.title}
          texturePath={item.texturePath}
          position={item.position}
          progress={progress}
          pulseIntensity={pulseIntensity}
          isModalOpen={isModalOpen}
          hoveredMesh={hoveredMesh}
          setHoveredMesh={setHoveredMesh}
          handleClick={handleClick}
        />
      ))}
      <mesh
        geometry={nodes.Ninth_Paper_Baked.geometry}
        material={newMaterials["Ninth_real_actual_Baked"]}
        position={[6.122, 6.808, -35.966]}
      />
    </group>
  );
}
